modLoader="javafml"
loaderVersion="[31,)"

issueTrackerURL="https://mrcrayfish.com/mods?id=glasscutter"

[[mods]]
modId="glasscutter"
version="1.0.0"
displayName="Glasscutter"
updateJSONURL="https://mrcrayfish.com/mods?id=glasscutter"
displayURL="https://mrcrayfish.com/mods?id=glasscutter"
logoFile="classcutter.png"
credits="@DarkestArgentum on Twitter for ideas"
authors="MrCrayfish"
description='Adds a glasscutter to cut different shapes with glass'

[[dependencies.improvedwolves]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.improvedwolves]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.16)"
    ordering="NONE"
    side="BOTH"
